// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using watchlistScreener.Server.Data;

#nullable disable

namespace watchlistScreener.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250504185018_Add Paises")]
    partial class AddPaises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("watchlistScreener.Server.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("watchlistScreener.Server.Models.Entities.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb29003e-c422-41a5-8bb3-02c6f6f7feba"),
                            Codigo = "AF",
                            Nombre = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("ad682fc9-38e8-4924-b71f-35099b8005eb"),
                            Codigo = "AL",
                            Nombre = "Albania"
                        },
                        new
                        {
                            Id = new Guid("64e752a8-bc85-4d44-85e9-ed079ecc7e04"),
                            Codigo = "DZ",
                            Nombre = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("5b842a69-9499-4dc4-9be6-1ae1f4667f20"),
                            Codigo = "AS",
                            Nombre = "American Samoa, United States"
                        },
                        new
                        {
                            Id = new Guid("c04e0760-4057-402b-8d64-ba5474707e45"),
                            Codigo = "AD",
                            Nombre = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("07960697-5ce1-4e5d-9e20-11fd06a6ebb8"),
                            Codigo = "AO",
                            Nombre = "Angola"
                        },
                        new
                        {
                            Id = new Guid("69b6ad75-c9be-45ac-a580-177af4793741"),
                            Codigo = "AI",
                            Nombre = "Anguilla, United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("6b1d8329-07f3-4991-aaee-1194d0e929d7"),
                            Codigo = "AG",
                            Nombre = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("d30043b7-9ced-41e3-9c36-6c07cd19ed7e"),
                            Codigo = "AR",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("cc8dea8f-acb1-4035-982f-df6353d9fd06"),
                            Codigo = "AM",
                            Nombre = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("d4edc19c-542f-45ac-9fbd-20a9d96cb2e1"),
                            Codigo = "AW",
                            Nombre = "Aruba"
                        },
                        new
                        {
                            Id = new Guid("17bc389d-9e34-49cd-b136-a96b0dcd13e6"),
                            Codigo = "AU",
                            Nombre = "Australia"
                        },
                        new
                        {
                            Id = new Guid("dc39b266-7bf8-4f97-86a0-0caf818d7011"),
                            Codigo = "AT",
                            Nombre = "Austria"
                        },
                        new
                        {
                            Id = new Guid("0b99b7f2-b01a-4296-bc62-4ce98d8497fe"),
                            Codigo = "AZ",
                            Nombre = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("68bab6e7-d3ae-4b7f-aa2d-942ed9e6e07b"),
                            Codigo = "BS",
                            Nombre = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("24ee5e70-cfe6-46c5-adde-789872807b42"),
                            Codigo = "BH",
                            Nombre = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("6defe922-f811-4afb-81e6-f66978e8d563"),
                            Codigo = "BD",
                            Nombre = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("616b4643-e363-4ba1-99fa-513ec353e523"),
                            Codigo = "BB",
                            Nombre = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("b2530d40-3e3f-4799-abea-99b2ed5e0343"),
                            Codigo = "BY",
                            Nombre = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("7fc62237-4a79-4071-9ac8-fad25f56a4f5"),
                            Codigo = "BE",
                            Nombre = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("fadfd2ff-c307-41ff-9b47-bdd986af8060"),
                            Codigo = "BZ",
                            Nombre = "Belize"
                        },
                        new
                        {
                            Id = new Guid("eba1de11-faf4-4162-9052-041233f1044d"),
                            Codigo = "BJ",
                            Nombre = "Benin"
                        },
                        new
                        {
                            Id = new Guid("56af8095-5280-4b04-a761-1c862eb5e317"),
                            Codigo = "BM",
                            Nombre = "Bermuda, United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("bc0886a9-83e8-459b-98fd-5c880974b2fb"),
                            Codigo = "BT",
                            Nombre = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("d565c05d-d54f-4e5d-829c-e01bf9fcd291"),
                            Codigo = "BO",
                            Nombre = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("97ac20f4-682f-4d55-85ea-585ef1ac6425"),
                            Codigo = "BQ",
                            Nombre = "Bonaire, Netherlands"
                        },
                        new
                        {
                            Id = new Guid("89310a2d-89fa-4d56-b153-2e5f0731018b"),
                            Codigo = "BA",
                            Nombre = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("0c580693-ef58-41ba-a012-1de1371e729e"),
                            Codigo = "BW",
                            Nombre = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("6c182dbd-96ed-4e72-b5f6-916c7c242c76"),
                            Codigo = "BR",
                            Nombre = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("04443509-2e34-4303-b26d-bf9ed611d4c3"),
                            Codigo = "VG",
                            Nombre = "British Virgin Islands, United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("68e0e3f6-45f4-4ff0-8eb5-f2a2a1ae55dc"),
                            Codigo = "BN",
                            Nombre = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("5e88db2c-9453-4535-9a87-e90103ee1b3c"),
                            Codigo = "BG",
                            Nombre = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("c6b53d16-c427-4574-a720-b061aa922534"),
                            Codigo = "BF",
                            Nombre = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("65c4a624-e04c-4d13-894e-0046df0a20d7"),
                            Codigo = "BI",
                            Nombre = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("94d8b720-3dca-4ee3-ab7a-3dc39696d689"),
                            Codigo = "CV",
                            Nombre = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("d7684d8d-3181-4ce0-8976-bc377cb1525f"),
                            Codigo = "KH",
                            Nombre = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("9f6786e5-68cc-491d-bc2b-e8b4df11aa23"),
                            Codigo = "CM",
                            Nombre = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("59505dec-cdf0-42eb-8b0b-c0e6aacda56b"),
                            Codigo = "CA",
                            Nombre = "Canada"
                        },
                        new
                        {
                            Id = new Guid("2e28347b-0c1a-41f1-8acf-7db104d559fe"),
                            Codigo = "KY",
                            Nombre = "Cayman Islands, United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("5ff89786-52b5-4bb5-9544-00fbd045698a"),
                            Codigo = "CF",
                            Nombre = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("eae0d86d-093a-474d-8c89-b1aa4576bea4"),
                            Codigo = "TD",
                            Nombre = "Chad"
                        },
                        new
                        {
                            Id = new Guid("16265cd1-f1b1-4747-a217-f7ce279571f3"),
                            Codigo = "CL",
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = new Guid("7f45c0c7-8f31-44e9-8adc-9496d38cfe63"),
                            Codigo = "CN",
                            Nombre = "China"
                        },
                        new
                        {
                            Id = new Guid("1055379b-9e39-4b0f-82e5-46520c6f058a"),
                            Codigo = "CO",
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("54e7a3c1-1317-46f2-b0bc-2da6c3237be1"),
                            Codigo = "KM",
                            Nombre = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("e066f248-6d57-483d-a80c-809eaac3a49d"),
                            Codigo = "CG",
                            Nombre = "Congo"
                        },
                        new
                        {
                            Id = new Guid("d5ddb81f-735d-4546-b9d8-29358bf49706"),
                            Codigo = "CD",
                            Nombre = "Congo (Democratic Republic of)"
                        },
                        new
                        {
                            Id = new Guid("3396adc4-901d-47fc-9d14-63625516cd9d"),
                            Codigo = "CR",
                            Nombre = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("98615b67-67a3-4b57-8c2c-307ef4c2d31c"),
                            Codigo = "HR",
                            Nombre = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("01ec4c4f-c48e-4dca-bdfc-b24c8bcbd983"),
                            Codigo = "CU",
                            Nombre = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("3e7bd1ba-3563-417c-8054-10800148a55c"),
                            Codigo = "CW",
                            Nombre = "Curaçao"
                        },
                        new
                        {
                            Id = new Guid("99ff1e02-0769-4974-8260-2b014e15bbaf"),
                            Codigo = "CY",
                            Nombre = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("8b223ec3-8f0d-4990-b27e-8ba704180fa2"),
                            Codigo = "CZ",
                            Nombre = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("e208a94f-1732-4599-ac61-ddc46686f357"),
                            Codigo = "CI",
                            Nombre = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = new Guid("d18cd18d-0644-41c5-b4c3-f5eb186f44ce"),
                            Codigo = "DK",
                            Nombre = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("9a703909-91bf-4ac4-a6ec-3c7b3ad9088f"),
                            Codigo = "DJ",
                            Nombre = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("78f044f9-8f36-44a2-86be-c824991fc2ab"),
                            Codigo = "DM",
                            Nombre = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("cd39cc01-c9cf-425e-bd32-84f9ca71bb36"),
                            Codigo = "DO",
                            Nombre = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("f11da8b4-72b7-4a7a-8b19-e96417eb95e2"),
                            Codigo = "EC",
                            Nombre = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("bde70f85-a357-499d-8e16-184998cd58fe"),
                            Codigo = "EG",
                            Nombre = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("33a1dcce-2354-4ef0-8b87-02160ec44b59"),
                            Codigo = "SV",
                            Nombre = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("01d9f210-f02a-453d-a917-bf56491fc4f5"),
                            Codigo = "GQ",
                            Nombre = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("7b64b7a3-5142-4e71-815f-f9b2f06ea485"),
                            Codigo = "ER",
                            Nombre = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("5525bc84-b82e-45dd-a568-4c607d58901c"),
                            Codigo = "EE",
                            Nombre = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("91ec3c08-9581-461f-9b40-9455f529747b"),
                            Codigo = "SZ",
                            Nombre = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("81f56c9f-d0d9-483a-9ed4-c0f81fc5df65"),
                            Codigo = "ET",
                            Nombre = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("d9bb33a5-ffd9-4c90-9ab3-975262df3b0c"),
                            Codigo = "AT,BE,BG,CY,DE,DK,EE,ES,FI,FR,GR,HR,HU,IE,IT,LT,LU,LV,MT,NL",
                            Nombre = "European Union"
                        },
                        new
                        {
                            Id = new Guid("d3bd7890-a9e2-42e9-b3ef-f1dead4483ff"),
                            Codigo = "FM",
                            Nombre = "Federated States of Micronesia"
                        },
                        new
                        {
                            Id = new Guid("e5820efe-a599-4fdf-bf6b-10f94695a300"),
                            Codigo = "FJ",
                            Nombre = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("2b86f30b-eb8b-4d89-a92a-38fd76438b34"),
                            Codigo = "FI",
                            Nombre = "Finland"
                        },
                        new
                        {
                            Id = new Guid("fa7a9f5e-a42a-40ea-b117-4743c03b3841"),
                            Codigo = "FR",
                            Nombre = "France"
                        },
                        new
                        {
                            Id = new Guid("191f316b-e767-43b2-b65f-d876f0563f99"),
                            Codigo = "GA",
                            Nombre = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("f6e9ff0a-4902-4a01-90e4-fa66540f3364"),
                            Codigo = "GM",
                            Nombre = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("424214c3-b50a-487e-95da-db9861669a01"),
                            Codigo = "GE",
                            Nombre = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("d13de921-2711-49e3-9873-9d7e53ab715a"),
                            Codigo = "DE",
                            Nombre = "Germany"
                        },
                        new
                        {
                            Id = new Guid("91942d29-a42e-48c9-9b1b-80e44da51d31"),
                            Codigo = "GH",
                            Nombre = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("3b424961-94d6-4c7d-a784-77d2ab5a6b41"),
                            Codigo = "GI",
                            Nombre = "Gibraltar, United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("952d64e4-bfee-405d-b199-52ee2c9248e8"),
                            Codigo = "GR",
                            Nombre = "Greece"
                        },
                        new
                        {
                            Id = new Guid("913f7b51-cced-4b58-b039-dcd8b5fe7b70"),
                            Codigo = "GD",
                            Nombre = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("e22402ce-a9f5-4ec7-b848-fbd8de296822"),
                            Codigo = "GT",
                            Nombre = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("98b6c2a8-54f2-4902-bd82-6c7db6d11ad5"),
                            Codigo = "GN",
                            Nombre = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("296e6471-bfc0-4e29-b8cf-57f84e6ed8e0"),
                            Codigo = "GW",
                            Nombre = "Guinea Bissau"
                        },
                        new
                        {
                            Id = new Guid("616c2290-da9a-4981-b74b-675799c15202"),
                            Codigo = "GY",
                            Nombre = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("be87fe8d-02b3-460a-b77d-f7dd7298b522"),
                            Codigo = "HT",
                            Nombre = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("19598843-6b3e-444a-964c-7d21020d97a2"),
                            Codigo = "HN",
                            Nombre = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("f91e2f8e-7ced-4d1c-a7a9-ff0bd84288a4"),
                            Codigo = "HK",
                            Nombre = "Hong Kong, China"
                        },
                        new
                        {
                            Id = new Guid("b1f47760-0828-4441-a18d-86ee965f9924"),
                            Codigo = "HU",
                            Nombre = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("f55ab587-7ed5-48b1-a546-a5bc632a83f1"),
                            Codigo = "914",
                            Nombre = "ICC (International Criminal Court)"
                        },
                        new
                        {
                            Id = new Guid("69d5bcb0-53aa-40fd-b070-dd2b04817a1a"),
                            Codigo = "IS",
                            Nombre = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("44765994-c197-4525-9bdc-7382f3effbfa"),
                            Codigo = "IN",
                            Nombre = "India"
                        },
                        new
                        {
                            Id = new Guid("9a52ed05-5af8-4419-88ce-80195ab24da1"),
                            Codigo = "ID",
                            Nombre = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("bd266a26-2edf-4e15-a5d9-293bcfcbe7b0"),
                            Codigo = "IR",
                            Nombre = "Iran"
                        },
                        new
                        {
                            Id = new Guid("85eea948-ccb7-48ad-aa85-4598ee55d9a5"),
                            Codigo = "IQ",
                            Nombre = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("d98ace5b-25be-489a-887b-3648ed4aee7b"),
                            Codigo = "IE",
                            Nombre = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("d791ddbe-167c-4239-bb89-6ac9604f4404"),
                            Codigo = "IL",
                            Nombre = "Israel"
                        },
                        new
                        {
                            Id = new Guid("162f3a5c-b5b7-4e79-90c3-591d5a36fed1"),
                            Codigo = "IT",
                            Nombre = "Italy"
                        },
                        new
                        {
                            Id = new Guid("5b30f591-20cd-4bbf-8629-c35fa10b2a2b"),
                            Codigo = "JM",
                            Nombre = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("998832d0-6d7f-4a83-a4c8-245168eac2c0"),
                            Codigo = "JP",
                            Nombre = "Japan"
                        },
                        new
                        {
                            Id = new Guid("2f76d88c-cf1f-4637-859d-6b4c2b19d55c"),
                            Codigo = "JO",
                            Nombre = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("4f3cdf9b-9c16-4a40-8539-0c0d3c544a98"),
                            Codigo = "KZ",
                            Nombre = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("1935727a-a121-4550-8625-cbb12e5edc26"),
                            Codigo = "KE",
                            Nombre = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("3c2f1cd7-ee8c-479a-90fa-ec7451ce61b1"),
                            Codigo = "KI",
                            Nombre = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("cbc53fbf-fff7-4405-8c28-074beda5fcda"),
                            Codigo = "KP",
                            Nombre = "Korea (Democratic People's Republic of)"
                        },
                        new
                        {
                            Id = new Guid("583eadaa-b856-46d2-86a5-7ebe91dd6c9b"),
                            Codigo = "KR",
                            Nombre = "Korea (Republic of)"
                        },
                        new
                        {
                            Id = new Guid("ba97cca7-a3d1-4d6e-9b47-85a0516b8fde"),
                            Codigo = "KW",
                            Nombre = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("a588d859-626a-40f8-99de-8cecee68e372"),
                            Codigo = "KG",
                            Nombre = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("3e3ecd33-5d54-4aef-8fc8-067250f11152"),
                            Codigo = "LA",
                            Nombre = "Laos"
                        },
                        new
                        {
                            Id = new Guid("9f106923-a7db-4b2d-bca4-50781d7dbec6"),
                            Codigo = "LV",
                            Nombre = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("16974e0d-cf4c-4a3d-8e43-29e72a9dd12d"),
                            Codigo = "LB",
                            Nombre = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("2ed8f913-0cf0-48b1-a5c0-77bd36942046"),
                            Codigo = "LS",
                            Nombre = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("ff24c00e-19f6-4b4c-9e34-4ca771af34fb"),
                            Codigo = "LR",
                            Nombre = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("8d3fd64c-e0e3-4af3-9bcc-1a933985770b"),
                            Codigo = "LY",
                            Nombre = "Libya"
                        },
                        new
                        {
                            Id = new Guid("b5257962-3670-4318-8f07-df3e6183ea3f"),
                            Codigo = "LI",
                            Nombre = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("df8e6e02-877c-41b1-8592-ca670149f51a"),
                            Codigo = "LT",
                            Nombre = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("e0f0e607-135c-4b58-9ef4-22c6af85f9dc"),
                            Codigo = "LU",
                            Nombre = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("1e08fa95-27d0-4556-b6a6-70145adff27d"),
                            Codigo = "MO",
                            Nombre = "Macao, China"
                        },
                        new
                        {
                            Id = new Guid("d35e78ef-aea1-48f0-bbf3-43640aab0e84"),
                            Codigo = "MG",
                            Nombre = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("a9ce8de6-d993-4847-861c-37b3afe19421"),
                            Codigo = "MW",
                            Nombre = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("71fd152f-3b29-4441-bc3b-9c7acad83150"),
                            Codigo = "MY",
                            Nombre = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("aca013ad-d8fb-4a95-9198-7680650c484e"),
                            Codigo = "MV",
                            Nombre = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("2edf66ca-526e-4549-ac79-e9de8424458c"),
                            Codigo = "ML",
                            Nombre = "Mali"
                        },
                        new
                        {
                            Id = new Guid("4098549f-d7ee-4b11-ac84-92e9aba9bf9f"),
                            Codigo = "MT",
                            Nombre = "Malta"
                        },
                        new
                        {
                            Id = new Guid("3e3e624c-bff2-419e-959a-16449340ddb1"),
                            Codigo = "MH",
                            Nombre = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("c76be378-b488-41d4-a226-151cbbd10d0e"),
                            Codigo = "MR",
                            Nombre = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("912f7edc-d547-465e-9c69-ae0be4735a27"),
                            Codigo = "MU",
                            Nombre = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("4be7749e-bf2e-48de-9371-1f70518de8d5"),
                            Codigo = "MX",
                            Nombre = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("80252ed2-374d-4dc5-b643-404f09374057"),
                            Codigo = "MD",
                            Nombre = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("ff2b29f5-f4dc-42b7-b70c-27f24b94fb58"),
                            Codigo = "MC",
                            Nombre = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("6e71e6b2-68a2-4f18-ab84-1f99c4eac6ef"),
                            Codigo = "MN",
                            Nombre = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("baa0fe09-d11c-48bf-a22d-92f131496b4e"),
                            Codigo = "ME",
                            Nombre = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("ee85b80e-e2c8-41ec-b702-e819841a00e6"),
                            Codigo = "MS",
                            Nombre = "Montserrat, United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("00620db8-f9b7-440f-b455-0fe7b0a68217"),
                            Codigo = "MA",
                            Nombre = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("f74314ca-fda5-4f13-b387-dacd24746309"),
                            Codigo = "MZ",
                            Nombre = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("60f247b8-1410-48b4-a57a-44852bc8e4da"),
                            Codigo = "MM",
                            Nombre = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("3e3fdee8-5467-419e-97c1-2581e5e0d767"),
                            Codigo = "NA",
                            Nombre = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("48997b6f-0d82-41b1-ab05-2fbc3302c96e"),
                            Codigo = "NR",
                            Nombre = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("55261cab-225e-4a64-ac22-562df80a28d0"),
                            Codigo = "NP",
                            Nombre = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("3da5152e-dbfd-4b1f-8c11-b04ac3859bbc"),
                            Codigo = "NL",
                            Nombre = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("109bcf17-d5a2-4df4-9215-a019010c73d6"),
                            Codigo = "NZ",
                            Nombre = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("c0df7e80-8371-4bc4-a3ca-0f29e9e31852"),
                            Codigo = "NI",
                            Nombre = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("0a2a3596-7062-4c70-9ff8-d2e89dcd467e"),
                            Codigo = "NE",
                            Nombre = "Niger"
                        },
                        new
                        {
                            Id = new Guid("38719d2f-0d6b-44e7-8380-5d999c0b17ab"),
                            Codigo = "NG",
                            Nombre = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("f6f4d0de-553c-4277-95fe-23b3e9f21dc6"),
                            Codigo = "MK",
                            Nombre = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("7d1132c8-b43c-442c-aad4-d35b47e54bf1"),
                            Codigo = "NO",
                            Nombre = "Norway"
                        },
                        new
                        {
                            Id = new Guid("08f7e5d5-9379-45a6-bb4d-64baa36e9ad6"),
                            Codigo = "OM",
                            Nombre = "Oman"
                        },
                        new
                        {
                            Id = new Guid("daaba39f-8b75-45e1-a0c8-09e7a9f94fee"),
                            Codigo = "PK",
                            Nombre = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("6d48c7c2-a27c-40c1-b169-27cb3139e900"),
                            Codigo = "PW",
                            Nombre = "Palau"
                        },
                        new
                        {
                            Id = new Guid("da3849a2-53de-40e7-b503-992844b17826"),
                            Codigo = "PS",
                            Nombre = "Palestine, State of"
                        },
                        new
                        {
                            Id = new Guid("8efa8eb3-fbc6-4650-a56b-84df5c337e71"),
                            Codigo = "PA",
                            Nombre = "Panama"
                        },
                        new
                        {
                            Id = new Guid("11c44856-7a8c-4883-a621-1cc20024af08"),
                            Codigo = "PG",
                            Nombre = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("8d595af9-1b4d-43ca-b204-2d6519872c93"),
                            Codigo = "PY",
                            Nombre = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("3b28bdae-d908-478b-9a15-3ca8200ec7c3"),
                            Codigo = "PE",
                            Nombre = "Peru"
                        },
                        new
                        {
                            Id = new Guid("532f0e0f-991a-4f6b-bf42-3e3dcc5ebdd9"),
                            Codigo = "PH",
                            Nombre = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("736b1c18-bda9-447f-8330-1e6f7ec3d996"),
                            Codigo = "PL",
                            Nombre = "Poland"
                        },
                        new
                        {
                            Id = new Guid("c9f99cf4-c7e5-4622-8cbf-a8b257289ca3"),
                            Codigo = "PT",
                            Nombre = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("36a320c5-04de-49d9-a2ca-4553ccd65955"),
                            Codigo = "PR",
                            Nombre = "Puerto Rico, United States"
                        },
                        new
                        {
                            Id = new Guid("517ebbcb-a710-48a6-8496-b4c51e0c8b86"),
                            Codigo = "QA",
                            Nombre = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("76578cb4-2f01-4799-973b-5fe27eaabe79"),
                            Codigo = "RO",
                            Nombre = "Romania"
                        },
                        new
                        {
                            Id = new Guid("be8e6c25-a3c4-4031-9ce2-58b0ff4c3a90"),
                            Codigo = "RU",
                            Nombre = "Russia"
                        },
                        new
                        {
                            Id = new Guid("82160f3f-3eb3-4830-8a0c-e85e9663d435"),
                            Codigo = "RW",
                            Nombre = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("fafcb720-3e0d-4e64-8abc-6425b847183a"),
                            Codigo = "916",
                            Nombre = "STL (Special Tribunal for Lebanon)"
                        },
                        new
                        {
                            Id = new Guid("93bf1334-4cd9-49fc-9f2e-3b461adec31f"),
                            Codigo = "KN",
                            Nombre = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("cb276fe8-d58e-4801-8887-bd68e1e30f2b"),
                            Codigo = "LC",
                            Nombre = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("3bf7a124-83e1-45a0-bee7-d421b895a430"),
                            Codigo = "VC",
                            Nombre = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("72a3d1a4-f234-4bf1-9657-20c11f17108c"),
                            Codigo = "WS",
                            Nombre = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("326d1da6-5ab3-495f-887d-ea6d2ff3f8a0"),
                            Codigo = "SM",
                            Nombre = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("8ad6460d-0d25-4c8a-aba8-867e01a22712"),
                            Codigo = "ST",
                            Nombre = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("ccef45ec-8c32-4f08-86e2-5eb589401d1e"),
                            Codigo = "SA",
                            Nombre = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("7a034094-f00d-4f30-9b7b-910896f8b790"),
                            Codigo = "SN",
                            Nombre = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("7721285f-b341-4a7b-919a-fed7577f25c1"),
                            Codigo = "RS",
                            Nombre = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("7d61e451-54a2-4fb8-a432-652ecf6418a7"),
                            Codigo = "SC",
                            Nombre = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("883e7ba4-fdda-4320-a516-ce36dc79c296"),
                            Codigo = "SL",
                            Nombre = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("32c3c66e-1752-4765-a030-203f599b89ea"),
                            Codigo = "SG",
                            Nombre = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("ad40eb29-9906-41b0-ab1a-633a0d3fe8c3"),
                            Codigo = "SX",
                            Nombre = "Sint Maarten"
                        },
                        new
                        {
                            Id = new Guid("a743201b-006c-4146-b1cd-8519f8086edd"),
                            Codigo = "SK",
                            Nombre = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("f2e33efa-6c4d-4b79-af76-ca11bc127216"),
                            Codigo = "SI",
                            Nombre = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("a4183410-86c1-49d3-99ee-0f998fff8a86"),
                            Codigo = "SB",
                            Nombre = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("70b0b318-4d6d-45fd-8f13-0cc2a0d4d539"),
                            Codigo = "SO",
                            Nombre = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("c865872d-b1d3-465e-981e-0107101a07c2"),
                            Codigo = "ZA",
                            Nombre = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("11418284-7934-4056-8be9-179650fed93d"),
                            Codigo = "SS",
                            Nombre = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("a883229d-ccc0-4567-9226-d4026b37fced"),
                            Codigo = "ES",
                            Nombre = "Spain"
                        },
                        new
                        {
                            Id = new Guid("1042bae8-3ac0-40dd-a043-2fa0d7e1e45d"),
                            Codigo = "LK",
                            Nombre = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("5d637d97-0c74-4a5b-bd40-b4a0ca154298"),
                            Codigo = "SD",
                            Nombre = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("76931b72-e30e-4f4f-b067-923739afb8df"),
                            Codigo = "SR",
                            Nombre = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("dc6e84e9-760a-4e4c-a609-2fe1862de5be"),
                            Codigo = "SE",
                            Nombre = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("f477f1b3-6e9c-4b37-aef1-391a84da01a0"),
                            Codigo = "CH",
                            Nombre = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("a850ebd4-0c01-435a-a9c8-1e79532ca4e2"),
                            Codigo = "SY",
                            Nombre = "Syria"
                        },
                        new
                        {
                            Id = new Guid("b8201ed4-fcf7-4f22-8cb2-fb0874b2f9d9"),
                            Codigo = "TW",
                            Nombre = "Taiwan, China"
                        },
                        new
                        {
                            Id = new Guid("d95fb4c0-9470-45fc-b372-72c3487a5d06"),
                            Codigo = "TJ",
                            Nombre = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("620f215f-a521-4ac2-8f4a-bb16e124d022"),
                            Codigo = "TZ",
                            Nombre = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("6a10ccd3-0da7-47cf-af45-c80168ee3552"),
                            Codigo = "TH",
                            Nombre = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("2011ba9d-279c-442e-afa1-c3557b2563f2"),
                            Codigo = "TL",
                            Nombre = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("d7fe994e-524e-45ef-895a-6f5b336216eb"),
                            Codigo = "TG",
                            Nombre = "Togo"
                        },
                        new
                        {
                            Id = new Guid("c3f5086a-afe9-4e40-9fbe-e3cab08e0e8e"),
                            Codigo = "TO",
                            Nombre = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("8e890c16-34fa-4f2c-bcd5-8fbcc60097c4"),
                            Codigo = "TT",
                            Nombre = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("a7876684-bd92-4242-be7a-7e8c321b9f11"),
                            Codigo = "TN",
                            Nombre = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("3da12317-f88d-4127-a26d-68845e4c2888"),
                            Codigo = "TM",
                            Nombre = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("789af701-0428-43fb-afe0-de24a82454b6"),
                            Codigo = "TC",
                            Nombre = "Turks and Caicos (Islands), United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("a99c4232-e2ee-4aec-946f-197b13dd2b15"),
                            Codigo = "TV",
                            Nombre = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("0c2b259a-3587-4b39-84d3-231e0742ecce"),
                            Codigo = "TR",
                            Nombre = "Türkiye"
                        },
                        new
                        {
                            Id = new Guid("625e7eb5-15c2-4e3d-9e22-e1e926db5260"),
                            Codigo = "922",
                            Nombre = "UN IRMCT (United Nations International Residual Mechanism for Criminal Tribunals) "
                        },
                        new
                        {
                            Id = new Guid("2e187b9c-2fb8-4a06-98c8-9d7799f992c0"),
                            Codigo = "UG",
                            Nombre = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("5148128e-fb06-4c5a-bde6-b339e7188299"),
                            Codigo = "UA",
                            Nombre = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("aebed0ca-6b35-41dd-86b2-1fe0c3e93ea3"),
                            Codigo = "AE",
                            Nombre = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("0589819d-92eb-4621-ad06-e0501a005d8e"),
                            Codigo = "GB",
                            Nombre = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("8779375e-96bd-4e0e-a2f6-be7ba92dced5"),
                            Codigo = "US",
                            Nombre = "United States"
                        },
                        new
                        {
                            Id = new Guid("8699e2fa-43e0-4ff8-876a-d3cd10f01622"),
                            Codigo = "UY",
                            Nombre = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("190aa0c3-6274-494c-a2d2-b6bc18581d18"),
                            Codigo = "UZ",
                            Nombre = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("c15e4b37-8f2e-44a9-ac30-e0e39e87c33f"),
                            Codigo = "VU",
                            Nombre = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("aa83f025-30a2-410d-bbe2-5d7906399efd"),
                            Codigo = "VA",
                            Nombre = "Vatican City State"
                        },
                        new
                        {
                            Id = new Guid("e10b3793-39b8-476c-92c8-4a011d7441c2"),
                            Codigo = "VE",
                            Nombre = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("694e0eb1-51d8-4af4-bde1-23ecbf36c63a"),
                            Codigo = "VN",
                            Nombre = "Viet Nam"
                        },
                        new
                        {
                            Id = new Guid("b69f48e9-0a8e-4191-bb62-9792d97d6aba"),
                            Codigo = "YE",
                            Nombre = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("a5b34e39-9159-4dc8-b815-2d1d3d5e0def"),
                            Codigo = "ZM",
                            Nombre = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("860d8823-e9ed-4c77-95f6-3683503dd322"),
                            Codigo = "ZW",
                            Nombre = "Zimbabwe"
                        },
                        new
                        {
                            Id = new Guid("8d67ab04-7154-42e4-b0f7-91ef81c87cf9"),
                            Codigo = "UNK",
                            Nombre = "under UNMIK mandate (Kosovo)"
                        });
                });

            modelBuilder.Entity("watchlistScreener.Server.Models.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionFisica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FacturacionAnual")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaUltimaEdicion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentificacionTributaria")
                        .HasColumnType("int");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefonico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SitioWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("watchlistScreener.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("watchlistScreener.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("watchlistScreener.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("watchlistScreener.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("watchlistScreener.Server.Models.Entities.Proveedor", b =>
                {
                    b.HasOne("watchlistScreener.Server.Models.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
