// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using watchlistScreener.Server.Data;

#nullable disable

namespace watchlistScreener.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("watchlistScreener.Server.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("watchlistScreener.Server.Models.Entities.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a123551-f97c-4f34-b30f-65d3e0bb4d7b"),
                            Codigo = "BW",
                            Nombre = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("29e79e81-6f2e-427a-9e30-eb7731402146"),
                            Codigo = "TO",
                            Nombre = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("04887b29-7bc2-4935-a268-e67388d58601"),
                            Codigo = "GR",
                            Nombre = "Grecia"
                        },
                        new
                        {
                            Id = new Guid("2642b83e-d9de-4b96-8d33-10efd24d1f86"),
                            Codigo = "MH",
                            Nombre = "Islas Marshall"
                        },
                        new
                        {
                            Id = new Guid("8c75f8ef-1082-40f2-96fc-c2cc23d55c53"),
                            Codigo = "BY",
                            Nombre = "Bielorrusia"
                        },
                        new
                        {
                            Id = new Guid("bd7a5a70-3c7a-43d2-9ded-b6929ae86ff3"),
                            Codigo = "CG",
                            Nombre = "Congo"
                        },
                        new
                        {
                            Id = new Guid("7ef3a7a3-eb77-4028-aeef-c677f4cf907b"),
                            Codigo = "TZ",
                            Nombre = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("55afe1e8-b328-4128-bfde-e7dae803eb55"),
                            Codigo = "LI",
                            Nombre = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("c3483946-8c63-4f00-8bd4-a02f40d306e6"),
                            Codigo = "SX",
                            Nombre = "Sint Maarten"
                        },
                        new
                        {
                            Id = new Guid("57797178-fb1b-45f0-907d-46069b57215f"),
                            Codigo = "BA",
                            Nombre = "Bosnia y Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("774ff9b4-1e84-4945-a0bc-98e7345f0e64"),
                            Codigo = "BH",
                            Nombre = "Bahrein"
                        },
                        new
                        {
                            Id = new Guid("9ded1731-afa5-4433-9b4d-a1b9ed1bb322"),
                            Codigo = "KE",
                            Nombre = "Kenia"
                        },
                        new
                        {
                            Id = new Guid("70292356-c3c7-4592-baae-edfa75446073"),
                            Codigo = "EE",
                            Nombre = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("1dc6d671-c094-4847-8d50-8f6d66d2dc8d"),
                            Codigo = "QA",
                            Nombre = "Catar"
                        },
                        new
                        {
                            Id = new Guid("33def8f3-7561-4bc0-8098-d88c504dbf0f"),
                            Codigo = "PL",
                            Nombre = "Polonia"
                        },
                        new
                        {
                            Id = new Guid("15e32b42-0163-4af4-9cd8-e960030331f2"),
                            Codigo = "MD",
                            Nombre = "Moldavia"
                        },
                        new
                        {
                            Id = new Guid("9162e7ad-23d5-4aea-a95a-4c87d31e765a"),
                            Codigo = "JO",
                            Nombre = "Jordania"
                        },
                        new
                        {
                            Id = new Guid("7c37bc02-1b0a-4b0c-9c33-82c76310d175"),
                            Codigo = "TN",
                            Nombre = "Túnez"
                        },
                        new
                        {
                            Id = new Guid("63a8f010-efc4-4cef-a764-d06d67270a95"),
                            Codigo = "PY",
                            Nombre = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("e055671f-497c-4f4a-91b8-5c69cd15e982"),
                            Codigo = "MY",
                            Nombre = "Malasia"
                        },
                        new
                        {
                            Id = new Guid("eb909cd8-9075-4bda-86d7-4402fbd9b104"),
                            Codigo = "CM",
                            Nombre = "Camerún"
                        },
                        new
                        {
                            Id = new Guid("6d590ec5-2453-45e6-9a9b-195e4e235ce8"),
                            Codigo = "SB",
                            Nombre = "Islas Salomón"
                        },
                        new
                        {
                            Id = new Guid("a2e8040f-5bd2-4b3f-83a1-235ade7c6ed4"),
                            Codigo = "MN",
                            Nombre = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("fc517473-77bb-49b0-97e3-3544dbfed1a1"),
                            Codigo = "VU",
                            Nombre = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("2c0f5675-485d-4a18-a193-9fa00d08fed5"),
                            Codigo = "NP",
                            Nombre = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("9a44fa72-4a93-4dce-a096-2453c0487f0f"),
                            Codigo = "GU",
                            Nombre = "Guam"
                        },
                        new
                        {
                            Id = new Guid("5b996f49-b707-4698-8aed-a3051c0d5ce3"),
                            Codigo = "LB",
                            Nombre = "Líbano"
                        },
                        new
                        {
                            Id = new Guid("07065449-c9e3-4446-b661-47ba6ecb519a"),
                            Codigo = "CI",
                            Nombre = "Costa de Marfil"
                        },
                        new
                        {
                            Id = new Guid("28305b90-df96-4773-b37b-5f4694654e6d"),
                            Codigo = "EC",
                            Nombre = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("6256f092-a05c-4b74-b469-7ec6cc24a736"),
                            Codigo = "PW",
                            Nombre = "Palau"
                        },
                        new
                        {
                            Id = new Guid("55366336-8325-4e95-8f87-d4e0d7d9a853"),
                            Codigo = "KG",
                            Nombre = "Kirguizistán"
                        },
                        new
                        {
                            Id = new Guid("b1144bf7-6e1a-4f70-b0f1-7a8cfb1a6f9f"),
                            Codigo = "EG",
                            Nombre = "Egipto"
                        },
                        new
                        {
                            Id = new Guid("c3f71149-5baa-4b7a-91ad-0d5bfa10802d"),
                            Codigo = "KP",
                            Nombre = "Corea del Norte"
                        },
                        new
                        {
                            Id = new Guid("2e7bbffb-d91c-4805-a083-86f68b8871a5"),
                            Codigo = "SN",
                            Nombre = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("069abf71-8422-41d2-8f4e-3d2802d27718"),
                            Codigo = "VG",
                            Nombre = "Islas Vírgenes del Reino Unido"
                        },
                        new
                        {
                            Id = new Guid("8530bafc-b878-4ea7-a2d5-4431814f3551"),
                            Codigo = "CR",
                            Nombre = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("3f625a21-ed15-4579-bbf5-55e477c3d63d"),
                            Codigo = "GT",
                            Nombre = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("fe9865a3-159d-4f6c-8e25-23e463878965"),
                            Codigo = "CN",
                            Nombre = "China"
                        },
                        new
                        {
                            Id = new Guid("373d50fa-c345-4fe1-9939-add39624ceb0"),
                            Codigo = "KZ",
                            Nombre = "Kazajistán"
                        },
                        new
                        {
                            Id = new Guid("df891446-797b-4efa-a2fa-a9ea4d0002f6"),
                            Codigo = "CV",
                            Nombre = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("1c0950cc-064a-4739-abbd-a459c0da2d7e"),
                            Codigo = "VA",
                            Nombre = "Ciudad del Vaticano"
                        },
                        new
                        {
                            Id = new Guid("c14e9e64-4ab3-48e7-ba7a-eaa2e41736ac"),
                            Codigo = "BT",
                            Nombre = "Bután"
                        },
                        new
                        {
                            Id = new Guid("805667fd-1e67-44a0-a30f-dc9f72ae89c4"),
                            Codigo = "CO",
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("f5fa2d63-c83a-45bc-80a6-6d0a955ee604"),
                            Codigo = "GD",
                            Nombre = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("8603a574-0692-4fdf-962b-04d1b44b760c"),
                            Codigo = "MP",
                            Nombre = "Islas Marianas del Norte"
                        },
                        new
                        {
                            Id = new Guid("ebfc7080-707b-402d-b91e-5e76c02cd583"),
                            Codigo = "PG",
                            Nombre = "Papúa Nueva Guinea"
                        },
                        new
                        {
                            Id = new Guid("1e8b932f-4e1c-479f-b5c5-2791e42a4271"),
                            Codigo = "AQ",
                            Nombre = "Antártida"
                        },
                        new
                        {
                            Id = new Guid("a4c158fd-32c0-4a93-8f29-002634ed03f3"),
                            Codigo = "ZA",
                            Nombre = "Sudáfrica"
                        },
                        new
                        {
                            Id = new Guid("78eff79a-9abe-4d30-aa26-a776e7a7338d"),
                            Codigo = "GN",
                            Nombre = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("6a0f8edd-4a1f-4300-bb99-3510f5459040"),
                            Codigo = "HK",
                            Nombre = "Hong Kong"
                        },
                        new
                        {
                            Id = new Guid("86b50876-f375-4de4-8580-96141263748d"),
                            Codigo = "TD",
                            Nombre = "Chad"
                        },
                        new
                        {
                            Id = new Guid("866909be-b10e-49a0-abca-c2c0a356e5d6"),
                            Codigo = "SH",
                            Nombre = "Santa Elena, Ascensión y Tristán de Acuña"
                        },
                        new
                        {
                            Id = new Guid("b8bdc1d3-bb00-442b-9f3f-5da09739dfc8"),
                            Codigo = "HN",
                            Nombre = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("edbb8a29-0690-4240-abfa-c23eee4e1afa"),
                            Codigo = "ME",
                            Nombre = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("153cb824-dc40-42af-8e45-fc7c46bb1d02"),
                            Codigo = "MA",
                            Nombre = "Marruecos"
                        },
                        new
                        {
                            Id = new Guid("73e8e174-335f-45eb-847d-d5adbc7b1175"),
                            Codigo = "NI",
                            Nombre = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("566607ca-be86-4601-b462-bc9b3acafd80"),
                            Codigo = "KY",
                            Nombre = "Islas Caimán"
                        },
                        new
                        {
                            Id = new Guid("cef334db-e528-4fc5-8b4d-c7a2ee1fc6f4"),
                            Codigo = "LU",
                            Nombre = "Luxemburgo"
                        },
                        new
                        {
                            Id = new Guid("ef0ed30d-61f5-4b08-b152-d4095d3b5ba5"),
                            Codigo = "GY",
                            Nombre = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("e9f88cc3-c824-4dc8-86ba-62375aa0ad65"),
                            Codigo = "BG",
                            Nombre = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("d7b7e468-a1d9-408f-b867-4af60dbb4b5f"),
                            Codigo = "GH",
                            Nombre = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("2d00b3ef-7d38-46d8-9b0a-44fea8c387ee"),
                            Codigo = "FI",
                            Nombre = "Finlandia"
                        },
                        new
                        {
                            Id = new Guid("2555f2c8-3435-4222-a344-eaffe17aa3e9"),
                            Codigo = "SC",
                            Nombre = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("0120084c-03ce-4c5f-933c-7a45f617162e"),
                            Codigo = "VI",
                            Nombre = "Islas Vírgenes de los Estados Unidos"
                        },
                        new
                        {
                            Id = new Guid("a967c691-b6f6-4eb3-b531-e8d3b931ed1c"),
                            Codigo = "ET",
                            Nombre = "Etiopía"
                        },
                        new
                        {
                            Id = new Guid("9fc8f54f-dc3b-4fac-bbfc-efc42c2b7d3c"),
                            Codigo = "MR",
                            Nombre = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("cfb3f1df-6fa9-440a-b418-0e2528d50488"),
                            Codigo = "IS",
                            Nombre = "Islandia"
                        },
                        new
                        {
                            Id = new Guid("43bcebd3-1285-4a91-bf39-4a2bf50cabfb"),
                            Codigo = "RE",
                            Nombre = "Reunión"
                        },
                        new
                        {
                            Id = new Guid("15829374-c08d-4eb8-b269-0c1ed852eab6"),
                            Codigo = "TJ",
                            Nombre = "Tayikistán"
                        },
                        new
                        {
                            Id = new Guid("f7b8952e-92aa-42a0-a9c8-9982e88905a2"),
                            Codigo = "CU",
                            Nombre = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("2a6dac3c-03ff-40f7-8db4-fc8b9b5f8aed"),
                            Codigo = "SO",
                            Nombre = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("11253029-0ae2-4fd7-829d-b3cf260b4039"),
                            Codigo = "CH",
                            Nombre = "Suiza"
                        },
                        new
                        {
                            Id = new Guid("66e213d8-b91d-42e4-a9b1-fefe3260670a"),
                            Codigo = "CX",
                            Nombre = "Isla de Navidad"
                        },
                        new
                        {
                            Id = new Guid("9da551ce-3e57-4490-bc80-24889e9944a8"),
                            Codigo = "MQ",
                            Nombre = "Martinica"
                        },
                        new
                        {
                            Id = new Guid("7c8c95b1-f1d3-4c75-a256-316161219ff3"),
                            Codigo = "AU",
                            Nombre = "Australia"
                        },
                        new
                        {
                            Id = new Guid("e0f618d8-79c4-4522-b0a3-1819bb338082"),
                            Codigo = "BJ",
                            Nombre = "Benín"
                        },
                        new
                        {
                            Id = new Guid("a69bdef2-29a5-4c85-8e34-5d4cfa57e302"),
                            Codigo = "LA",
                            Nombre = "Laos"
                        },
                        new
                        {
                            Id = new Guid("80698799-cb5b-48b5-898a-a255c230c6bb"),
                            Codigo = "SD",
                            Nombre = "Sudán"
                        },
                        new
                        {
                            Id = new Guid("7f56a383-04ea-4842-b30c-fecf146737d0"),
                            Codigo = "LY",
                            Nombre = "Libia"
                        },
                        new
                        {
                            Id = new Guid("dfaa491f-da0b-4ed7-847b-3704f422bf74"),
                            Codigo = "ML",
                            Nombre = "Mali"
                        },
                        new
                        {
                            Id = new Guid("c1f35f07-9d37-401a-b0fa-316c6b2309a4"),
                            Codigo = "PE",
                            Nombre = "Perú"
                        },
                        new
                        {
                            Id = new Guid("00c50a5c-a946-4c33-a676-37ca6ae3a150"),
                            Codigo = "HU",
                            Nombre = "Hungría"
                        },
                        new
                        {
                            Id = new Guid("218f28d1-55f2-444d-8b75-cf28fbe8cb3d"),
                            Codigo = "BM",
                            Nombre = "Bermudas"
                        },
                        new
                        {
                            Id = new Guid("ff36ac4d-a836-4153-ac1b-2523df6fd85a"),
                            Codigo = "FJ",
                            Nombre = "Fiyi"
                        },
                        new
                        {
                            Id = new Guid("aab51c5c-569c-4489-b982-166b8eb6548b"),
                            Codigo = "NL",
                            Nombre = "Países Bajos"
                        },
                        new
                        {
                            Id = new Guid("2f0e9eee-8796-446d-a100-161e17b8b061"),
                            Codigo = "NG",
                            Nombre = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("95f35a8a-3bbf-4900-b85f-2fae4dbba5fc"),
                            Codigo = "PT",
                            Nombre = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("1192cc02-3920-4064-8f39-6bdf2f14d0df"),
                            Codigo = "IN",
                            Nombre = "India"
                        },
                        new
                        {
                            Id = new Guid("9f46cb94-7ae0-4bad-b52e-480068158a6c"),
                            Codigo = "GS",
                            Nombre = "Islas Georgias del Sur y Sandwich del Sur"
                        },
                        new
                        {
                            Id = new Guid("e577dd35-6925-4745-9e6f-11966cf6455c"),
                            Codigo = "LS",
                            Nombre = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("73383825-49b2-4c25-8b6b-a63252092738"),
                            Codigo = "ZM",
                            Nombre = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("9e4919f6-b01d-4bbf-a0e0-69a6214f9833"),
                            Codigo = "TK",
                            Nombre = "Islas Tokelau"
                        },
                        new
                        {
                            Id = new Guid("16f45316-7e79-4198-9a6a-4796efa5dfb0"),
                            Codigo = "GM",
                            Nombre = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("50db5220-56ea-428b-9c6b-0553c3fdb731"),
                            Codigo = "SL",
                            Nombre = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("3a37cf79-7e20-493b-97e0-704c89442ad8"),
                            Codigo = "KI",
                            Nombre = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("8b8c6267-4333-451b-9b7c-b2c96ffcb578"),
                            Codigo = "NO",
                            Nombre = "Noruega"
                        },
                        new
                        {
                            Id = new Guid("16948ff4-180c-4b0e-ab76-60ecbcdac946"),
                            Codigo = "IE",
                            Nombre = "Irlanda"
                        },
                        new
                        {
                            Id = new Guid("f96f8e2a-8711-4a5a-80e2-ec08a4d59a26"),
                            Codigo = "GL",
                            Nombre = "Groenlandia"
                        },
                        new
                        {
                            Id = new Guid("53321c78-fbde-447b-b693-59ade948943f"),
                            Codigo = "IO",
                            Nombre = "Territorio Británico del Océano Índico"
                        },
                        new
                        {
                            Id = new Guid("0d78fe0f-8d67-4251-af84-6a3ba46da075"),
                            Codigo = "MZ",
                            Nombre = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("c25fcfb0-7464-461d-abb9-770c7de86ed1"),
                            Codigo = "PA",
                            Nombre = "Panamá"
                        },
                        new
                        {
                            Id = new Guid("29d8db58-2e81-4ceb-b101-95ebb674ac95"),
                            Codigo = "UA",
                            Nombre = "Ucrania"
                        },
                        new
                        {
                            Id = new Guid("69e1ba48-f092-4d22-9dcd-9a33618cbfc8"),
                            Codigo = "UY",
                            Nombre = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("3edd0bdf-ba32-425a-b7c6-4cce725df938"),
                            Codigo = "AW",
                            Nombre = "Aruba"
                        },
                        new
                        {
                            Id = new Guid("2fdf5051-8417-43d8-8377-d04f762ed602"),
                            Codigo = "IR",
                            Nombre = "Iran"
                        },
                        new
                        {
                            Id = new Guid("3af6d118-322b-477d-9ec1-1ca337df03d4"),
                            Codigo = "IM",
                            Nombre = "Isla de Man"
                        },
                        new
                        {
                            Id = new Guid("f2c536ab-f0b0-42a8-8045-64d3ec960da7"),
                            Codigo = "AX",
                            Nombre = "Alandia"
                        },
                        new
                        {
                            Id = new Guid("a3eb8a72-a213-43f0-ad6b-5b0811c1e458"),
                            Codigo = "SA",
                            Nombre = "Arabia Saudí"
                        },
                        new
                        {
                            Id = new Guid("9cf7d04c-5ec4-44fc-af47-5c409a1f315c"),
                            Codigo = "DJ",
                            Nombre = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("d55d90ab-63cc-4c1c-a007-7c623c2b2fa8"),
                            Codigo = "IT",
                            Nombre = "Italia"
                        },
                        new
                        {
                            Id = new Guid("a7c29582-6cd0-4558-a81a-ad5a84f59ee1"),
                            Codigo = "CA",
                            Nombre = "Canadá"
                        },
                        new
                        {
                            Id = new Guid("eb82f569-26c5-45fd-92da-cec316b412c7"),
                            Codigo = "JM",
                            Nombre = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("a1234c79-4c10-4cdd-937f-7c4b6d49075a"),
                            Codigo = "NE",
                            Nombre = "Níger"
                        },
                        new
                        {
                            Id = new Guid("e4e5b3ca-6d13-4d3e-8a6e-5699c4e335f4"),
                            Codigo = "AF",
                            Nombre = "Afganistán"
                        },
                        new
                        {
                            Id = new Guid("f687dd04-c29f-4d78-88af-319e87b6f64d"),
                            Codigo = "HR",
                            Nombre = "Croacia"
                        },
                        new
                        {
                            Id = new Guid("14afd52c-dd47-4cc1-8161-9debfda7c2be"),
                            Codigo = "LV",
                            Nombre = "Letonia"
                        },
                        new
                        {
                            Id = new Guid("a2090c26-741a-44dd-9390-eafd92dba7c8"),
                            Codigo = "WS",
                            Nombre = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("66e678e9-c74b-45da-a472-f9807140288a"),
                            Codigo = "CW",
                            Nombre = "Curazao"
                        },
                        new
                        {
                            Id = new Guid("434c1c8d-895a-4841-8203-c43fc93c46f9"),
                            Codigo = "CY",
                            Nombre = "Chipre"
                        },
                        new
                        {
                            Id = new Guid("5803c685-e5ab-4a11-bafa-3b42a1efb827"),
                            Codigo = "MG",
                            Nombre = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("42d33ce1-3fd1-4c3c-819f-3f98b57df15c"),
                            Codigo = "UZ",
                            Nombre = "Uzbekistán"
                        },
                        new
                        {
                            Id = new Guid("4d845dff-b0d6-4421-b168-53b7226b69df"),
                            Codigo = "MO",
                            Nombre = "Macao"
                        },
                        new
                        {
                            Id = new Guid("cabb83eb-855c-4338-aca5-1771d2f32084"),
                            Codigo = "FM",
                            Nombre = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("92826d7c-418d-4345-b0c3-8237572c3054"),
                            Codigo = "MV",
                            Nombre = "Maldivas"
                        },
                        new
                        {
                            Id = new Guid("75c928c8-0e28-4c88-95fe-d091fc0c16e9"),
                            Codigo = "SI",
                            Nombre = "Eslovenia"
                        },
                        new
                        {
                            Id = new Guid("b0f1ca4e-641c-4bab-9c82-d68f53ffa097"),
                            Codigo = "AD",
                            Nombre = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("4b038013-9709-4621-ad09-158b94b9dfcb"),
                            Codigo = "ER",
                            Nombre = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("02b6a498-28e1-44f4-945d-caeb78e0a37b"),
                            Codigo = "GW",
                            Nombre = "Guinea-Bisáu"
                        },
                        new
                        {
                            Id = new Guid("207af4eb-9c90-47b3-944b-9710962f0f59"),
                            Codigo = "KW",
                            Nombre = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("de57c088-0e3f-40ec-b222-797d0e09cb02"),
                            Codigo = "GA",
                            Nombre = "Gabón"
                        },
                        new
                        {
                            Id = new Guid("f8a23d51-a851-40a4-80e7-d040c87aa17e"),
                            Codigo = "YE",
                            Nombre = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("a39d656b-e536-48ae-8f0a-d0c6b1945c87"),
                            Codigo = "CC",
                            Nombre = "Islas Cocos o Islas Keeling"
                        },
                        new
                        {
                            Id = new Guid("a33fbad3-b691-4d0d-be44-f0ea261e71a4"),
                            Codigo = "TL",
                            Nombre = "Timor Oriental"
                        },
                        new
                        {
                            Id = new Guid("dd426855-6952-4463-933d-a8658ee69648"),
                            Codigo = "SK",
                            Nombre = "República Eslovaca"
                        },
                        new
                        {
                            Id = new Guid("2eea36a2-3789-4829-afd5-c57171f5dfe0"),
                            Codigo = "RW",
                            Nombre = "Ruanda"
                        },
                        new
                        {
                            Id = new Guid("5d2857c3-6b6f-409a-869c-736644ce5eff"),
                            Codigo = "AG",
                            Nombre = "Antigua y Barbuda"
                        },
                        new
                        {
                            Id = new Guid("20349fa7-5805-4235-a554-f183270decac"),
                            Codigo = "TG",
                            Nombre = "Togo"
                        },
                        new
                        {
                            Id = new Guid("00a8409f-00b8-45b3-9608-d2fa873e19df"),
                            Codigo = "SY",
                            Nombre = "Siria"
                        },
                        new
                        {
                            Id = new Guid("1b957d4f-3c7a-4678-bcab-ff3bb51ab273"),
                            Codigo = "GP",
                            Nombre = "Guadalupe"
                        },
                        new
                        {
                            Id = new Guid("8ab84da6-fc1f-4a3a-82fe-617b5ecdefb3"),
                            Codigo = "TM",
                            Nombre = "Turkmenistán"
                        },
                        new
                        {
                            Id = new Guid("281ed329-46ef-48ca-88e6-86fa9d7c9241"),
                            Codigo = "LK",
                            Nombre = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("86d53d1e-b663-4006-9d3d-b6876e9f120c"),
                            Codigo = "US",
                            Nombre = "Estados Unidos"
                        },
                        new
                        {
                            Id = new Guid("39f2c768-5f1f-42da-b66b-7ff2a0414c5b"),
                            Codigo = "AR",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("b4b7a40f-e7b9-401c-af4a-5e69b2b1200d"),
                            Codigo = "SS",
                            Nombre = "Sudán del Sur"
                        },
                        new
                        {
                            Id = new Guid("f9443106-5947-44f9-a8e9-435e3ff19d29"),
                            Codigo = "PS",
                            Nombre = "Palestina"
                        },
                        new
                        {
                            Id = new Guid("8ff46c0f-55d1-47eb-aa46-f99a37b31dd8"),
                            Codigo = "GE",
                            Nombre = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("cb01d263-9d41-4092-8764-47991586effc"),
                            Codigo = "JP",
                            Nombre = "Japón"
                        },
                        new
                        {
                            Id = new Guid("20847316-f585-4844-b923-065e830a56b1"),
                            Codigo = "SE",
                            Nombre = "Suecia"
                        },
                        new
                        {
                            Id = new Guid("0ff78adc-3558-4fca-9458-aa86c0ea6bf6"),
                            Codigo = "CL",
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = new Guid("d25296da-bad1-4739-9884-db73140fdb82"),
                            Codigo = "KN",
                            Nombre = "San Cristóbal y Nieves"
                        },
                        new
                        {
                            Id = new Guid("630f5333-8279-437a-a0ed-a52a7a2f2f03"),
                            Codigo = "DK",
                            Nombre = "Dinamarca"
                        },
                        new
                        {
                            Id = new Guid("7efda655-9102-4dc5-94cf-5064e65c0632"),
                            Codigo = "UM",
                            Nombre = "Islas Ultramarinas Menores de Estados Unidos"
                        },
                        new
                        {
                            Id = new Guid("6b5b9c68-e859-4f2d-bb4d-75b993f4bafe"),
                            Codigo = "AS",
                            Nombre = "Samoa Americana"
                        },
                        new
                        {
                            Id = new Guid("5ee35fe1-ebec-4365-af53-abe6f7b9d3d0"),
                            Codigo = "AI",
                            Nombre = "Anguilla"
                        },
                        new
                        {
                            Id = new Guid("aae84a38-dd8b-49d4-b245-764890a915eb"),
                            Codigo = "PH",
                            Nombre = "Filipinas"
                        },
                        new
                        {
                            Id = new Guid("8ab9442a-1eea-42bb-9f1d-bac0a98c1af0"),
                            Codigo = "BO",
                            Nombre = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("422574d2-85b0-4642-b7c6-c269933f5688"),
                            Codigo = "ST",
                            Nombre = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = new Guid("8ce4aa67-66a3-4aa6-b184-649aabf76802"),
                            Codigo = "MS",
                            Nombre = "Montserrat"
                        },
                        new
                        {
                            Id = new Guid("0cac11f0-8f91-44cd-8834-c0ea96c84e51"),
                            Codigo = "MM",
                            Nombre = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("eeb4b16b-6dbd-4a85-8f7b-c1559d174668"),
                            Codigo = "NU",
                            Nombre = "Niue"
                        },
                        new
                        {
                            Id = new Guid("869cce88-fd7f-4da0-a1b7-c32aef105a94"),
                            Codigo = "IL",
                            Nombre = "Israel"
                        },
                        new
                        {
                            Id = new Guid("2fe8bbe9-e109-4562-925e-ef7bbefff534"),
                            Codigo = "HM",
                            Nombre = "Islas Heard y McDonald"
                        },
                        new
                        {
                            Id = new Guid("5e6403b9-0935-46ee-914a-1ef24196e4a8"),
                            Codigo = "KM",
                            Nombre = "Comoras"
                        },
                        new
                        {
                            Id = new Guid("be15b58a-34ca-4be2-8e96-d89cdbfb9550"),
                            Codigo = "VC",
                            Nombre = "San Vicente y Granadinas"
                        },
                        new
                        {
                            Id = new Guid("83d0ccdc-df64-466e-ba6f-34d9cf2a5176"),
                            Codigo = "VN",
                            Nombre = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("8bad89d3-11cc-4fae-a5a2-45ebecdf5a7a"),
                            Codigo = "BQ",
                            Nombre = "Caribe Neerlandés"
                        },
                        new
                        {
                            Id = new Guid("a131ea74-ce81-4381-9de1-d5be68cceb23"),
                            Codigo = "JE",
                            Nombre = "Jersey"
                        },
                        new
                        {
                            Id = new Guid("c60af867-8efe-48af-85c6-94c964d2d3da"),
                            Codigo = "FK",
                            Nombre = "Islas Malvinas"
                        },
                        new
                        {
                            Id = new Guid("a0901c3c-4678-4610-9eb3-9208bdc078ca"),
                            Codigo = "AM",
                            Nombre = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("04f3b16d-5437-4f09-bf7a-8c9452cbb0f3"),
                            Codigo = "XK",
                            Nombre = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("38446f2b-c4f4-4755-92c9-76c8ed85761c"),
                            Codigo = "BV",
                            Nombre = "Isla Bouvet"
                        },
                        new
                        {
                            Id = new Guid("a948a4ab-d495-41ce-a8ed-d0285b580f3f"),
                            Codigo = "VE",
                            Nombre = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("36735441-22b1-47f9-9dbe-f0dfe8a0d6a6"),
                            Codigo = "BE",
                            Nombre = "Bélgica"
                        },
                        new
                        {
                            Id = new Guid("3c5d56dd-05cb-4c01-bac1-c9287131bb9c"),
                            Codigo = "BF",
                            Nombre = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("5118c961-45ad-4c68-88e3-7da271c14878"),
                            Codigo = "DZ",
                            Nombre = "Argelia"
                        },
                        new
                        {
                            Id = new Guid("029bb73b-8ad1-42c2-9cf3-a4974ced857f"),
                            Codigo = "FR",
                            Nombre = "Francia"
                        },
                        new
                        {
                            Id = new Guid("7664810d-6d79-4b39-9e92-10085e25f6e8"),
                            Codigo = "PM",
                            Nombre = "San Pedro y Miquelón"
                        },
                        new
                        {
                            Id = new Guid("4f41d0f2-d586-488d-bd29-de20c40d9413"),
                            Codigo = "PK",
                            Nombre = "Pakistán"
                        },
                        new
                        {
                            Id = new Guid("7943c322-79ec-4d98-b6d1-57d85fdf1419"),
                            Codigo = "SV",
                            Nombre = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("83f50e3a-5509-428b-8a08-a45eb15791dd"),
                            Codigo = "MK",
                            Nombre = "Macedonia del Norte"
                        },
                        new
                        {
                            Id = new Guid("8d7811d6-2ec2-4461-9bdb-f08b7a692a11"),
                            Codigo = "BN",
                            Nombre = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("d4b2eb3a-5967-4257-99a4-8ae21c876cdd"),
                            Codigo = "CF",
                            Nombre = "República Centroafricana"
                        },
                        new
                        {
                            Id = new Guid("7ebaeef6-9f22-4476-8bbf-9e524b028cd8"),
                            Codigo = "UG",
                            Nombre = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("33cde7a3-18a8-40ed-ba37-a307bf2407ec"),
                            Codigo = "WF",
                            Nombre = "Wallis y Futuna"
                        },
                        new
                        {
                            Id = new Guid("bb671c91-fa45-41f7-af49-7f6d8a12bf11"),
                            Codigo = "DE",
                            Nombre = "Alemania"
                        },
                        new
                        {
                            Id = new Guid("2ad7003e-b983-4b11-965b-20c6513d199f"),
                            Codigo = "TW",
                            Nombre = "Taiwán"
                        },
                        new
                        {
                            Id = new Guid("cbcb028d-002a-4a5d-b390-cf36a91de7f4"),
                            Codigo = "AE",
                            Nombre = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = new Guid("f83880c5-7fd8-460b-8642-b96579f05dfb"),
                            Codigo = "NA",
                            Nombre = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("6da02812-b230-4f0c-bb2e-7d21a831769a"),
                            Codigo = "MC",
                            Nombre = "Mónaco"
                        },
                        new
                        {
                            Id = new Guid("374c01bd-db21-4b49-8905-6a9039cb7eeb"),
                            Codigo = "MW",
                            Nombre = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("a0274691-a232-4fee-9ddd-95567ad5c4dc"),
                            Codigo = "AZ",
                            Nombre = "Azerbaiyán"
                        },
                        new
                        {
                            Id = new Guid("5baf91f7-3b29-4725-b13d-76ba2a69717c"),
                            Codigo = "MX",
                            Nombre = "México"
                        },
                        new
                        {
                            Id = new Guid("5e0c8ed3-cdc0-498a-a2e1-6f24916f1412"),
                            Codigo = "IQ",
                            Nombre = "Irak"
                        },
                        new
                        {
                            Id = new Guid("9594cedf-a710-490c-b914-ce172bfa6ac7"),
                            Codigo = "KH",
                            Nombre = "Camboya"
                        },
                        new
                        {
                            Id = new Guid("6fed55e1-babe-4e8f-aaec-85d159cc1202"),
                            Codigo = "TV",
                            Nombre = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("639a28d9-68e4-48d2-a250-81f08f9c0caa"),
                            Codigo = "CK",
                            Nombre = "Islas Cook"
                        },
                        new
                        {
                            Id = new Guid("45b386f1-cd2f-4cf0-bb68-49a1ef970794"),
                            Codigo = "HT",
                            Nombre = "Haití"
                        },
                        new
                        {
                            Id = new Guid("8b31e921-c25f-4752-b8c0-5ce2e4531892"),
                            Codigo = "BZ",
                            Nombre = "Belice"
                        },
                        new
                        {
                            Id = new Guid("e834051c-b1db-430a-8a31-ee4bdc9364ba"),
                            Codigo = "GF",
                            Nombre = "Guayana Francesa"
                        },
                        new
                        {
                            Id = new Guid("8a925b86-57e2-4e3c-999e-8f3d905be075"),
                            Codigo = "CD",
                            Nombre = "Congo (Rep. Dem.)"
                        },
                        new
                        {
                            Id = new Guid("711686c1-2d56-4c04-9982-8ea277a67aea"),
                            Codigo = "GQ",
                            Nombre = "Guinea Ecuatorial"
                        },
                        new
                        {
                            Id = new Guid("5d7ba3ed-9cd1-4883-b36e-875598ab10bc"),
                            Codigo = "MU",
                            Nombre = "Mauricio"
                        },
                        new
                        {
                            Id = new Guid("a6d8e374-6543-48bc-a605-4838813b503b"),
                            Codigo = "AT",
                            Nombre = "Austria"
                        },
                        new
                        {
                            Id = new Guid("9c5402cf-a319-4a1e-85e8-0eca4e15157a"),
                            Codigo = "ES",
                            Nombre = "España"
                        },
                        new
                        {
                            Id = new Guid("1891068c-b50b-4ca0-a566-7b96b00a973b"),
                            Codigo = "RU",
                            Nombre = "Rusia"
                        },
                        new
                        {
                            Id = new Guid("74bd22b6-124a-44eb-8ccf-8ba1f6f4873d"),
                            Codigo = "ZW",
                            Nombre = "Zimbabue"
                        },
                        new
                        {
                            Id = new Guid("ab6505f6-6638-40fd-ab77-469e22dad100"),
                            Codigo = "SG",
                            Nombre = "Singapur"
                        },
                        new
                        {
                            Id = new Guid("1824dce2-8efd-404f-868e-7e11bc8d1f05"),
                            Codigo = "CZ",
                            Nombre = "Chequia"
                        },
                        new
                        {
                            Id = new Guid("a15973ac-edf4-4119-9506-51b693efbbd9"),
                            Codigo = "FO",
                            Nombre = "Islas Faroe"
                        },
                        new
                        {
                            Id = new Guid("8dca6c1b-feb5-4d4c-a2d4-33e0636c63e1"),
                            Codigo = "OM",
                            Nombre = "Omán"
                        },
                        new
                        {
                            Id = new Guid("df91f327-6dfa-4dfa-bb68-88bf800236f6"),
                            Codigo = "TF",
                            Nombre = "Tierras Australes y Antárticas Francesas"
                        },
                        new
                        {
                            Id = new Guid("cded149c-9541-48bc-9c75-7674dc7d1c39"),
                            Codigo = "BI",
                            Nombre = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("a9a1d7dd-9b7b-418c-aba8-cbcc500fb9aa"),
                            Codigo = "EH",
                            Nombre = "Sahara Occidental"
                        },
                        new
                        {
                            Id = new Guid("9382f873-94ee-4573-b81e-809392855612"),
                            Codigo = "YT",
                            Nombre = "Mayotte"
                        },
                        new
                        {
                            Id = new Guid("4f091e9a-d45c-4b79-8ea2-5097558ff5cb"),
                            Codigo = "PR",
                            Nombre = "Puerto Rico"
                        },
                        new
                        {
                            Id = new Guid("14f99c1a-0e1d-4ab6-b10f-ee10d797f670"),
                            Codigo = "SM",
                            Nombre = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("42532ddc-5daf-4954-9135-09b1143a45b8"),
                            Codigo = "TC",
                            Nombre = "Islas Turks y Caicos"
                        },
                        new
                        {
                            Id = new Guid("bf415dbb-782d-4626-adfe-ff42d8cfbd5a"),
                            Codigo = "MT",
                            Nombre = "Malta"
                        },
                        new
                        {
                            Id = new Guid("6197ab51-147f-4ca8-93b4-3ba072a8d5d1"),
                            Codigo = "NR",
                            Nombre = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("d5338524-6d3b-407a-8926-f7f8f703df2a"),
                            Codigo = "MF",
                            Nombre = "Saint Martin"
                        },
                        new
                        {
                            Id = new Guid("e50b8079-a324-4607-a61e-d724391cc725"),
                            Codigo = "PF",
                            Nombre = "Polinesia Francesa"
                        },
                        new
                        {
                            Id = new Guid("a7388a5c-c1bc-4e93-bb00-fcc719edcbf1"),
                            Codigo = "NZ",
                            Nombre = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = new Guid("968186d7-2ca4-4a10-af20-5af09c4fc5ab"),
                            Codigo = "RS",
                            Nombre = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("269bf09e-d69b-4c92-a05b-6593e2b7f237"),
                            Codigo = "TT",
                            Nombre = "Trinidad y Tobago"
                        },
                        new
                        {
                            Id = new Guid("ccabb518-5ed6-42ba-9895-bbe60014f102"),
                            Codigo = "BL",
                            Nombre = "San Bartolomé"
                        },
                        new
                        {
                            Id = new Guid("5e880adc-708c-47c5-a13b-96674b2033db"),
                            Codigo = "PN",
                            Nombre = "Islas Pitcairn"
                        },
                        new
                        {
                            Id = new Guid("e3a3ee06-5230-46eb-897b-60865ec74351"),
                            Codigo = "NF",
                            Nombre = "Isla de Norfolk"
                        },
                        new
                        {
                            Id = new Guid("8061cf72-f915-40b2-90a5-77162068e221"),
                            Codigo = "BB",
                            Nombre = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("c95887d8-1c90-4798-8957-c7aff0dbc181"),
                            Codigo = "KR",
                            Nombre = "Corea del Sur"
                        },
                        new
                        {
                            Id = new Guid("02c4d95c-7830-4fb6-bdce-bae508943b43"),
                            Codigo = "BD",
                            Nombre = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("4a205056-87e2-445e-ae12-48f4b7ee57cb"),
                            Codigo = "DO",
                            Nombre = "República Dominicana"
                        },
                        new
                        {
                            Id = new Guid("73636a54-ae1b-40b3-be87-4a7326f83d0e"),
                            Codigo = "TR",
                            Nombre = "Turquía"
                        },
                        new
                        {
                            Id = new Guid("99e68782-dcdb-400b-a0f7-da739bbd44fa"),
                            Codigo = "ID",
                            Nombre = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("a85b7b9e-01ec-4b91-9949-e7cda02a5113"),
                            Codigo = "LR",
                            Nombre = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("0d7ddd52-ca3e-4834-9bf8-21dddc6a1420"),
                            Codigo = "GG",
                            Nombre = "Guernsey"
                        },
                        new
                        {
                            Id = new Guid("d7a06de2-bbb3-4f71-b277-7a01200e0963"),
                            Codigo = "SR",
                            Nombre = "Surinam"
                        },
                        new
                        {
                            Id = new Guid("b84ae9d3-6907-42fe-8fbc-a02f1280f2d7"),
                            Codigo = "AL",
                            Nombre = "Albania"
                        },
                        new
                        {
                            Id = new Guid("64229f03-02a5-4aa4-a0e2-218a731ca34d"),
                            Codigo = "DM",
                            Nombre = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("a47c6a19-82f8-485b-9783-5fa70d5da743"),
                            Codigo = "TH",
                            Nombre = "Tailandia"
                        },
                        new
                        {
                            Id = new Guid("b0b6e57e-77fe-494d-bac7-2abda64f6954"),
                            Codigo = "GB",
                            Nombre = "Reino Unido"
                        },
                        new
                        {
                            Id = new Guid("468c202b-b780-4688-bb91-e550de7c48f2"),
                            Codigo = "NC",
                            Nombre = "Nueva Caledonia"
                        },
                        new
                        {
                            Id = new Guid("3563a719-2d00-4f03-85a4-59aad03c8c6b"),
                            Codigo = "RO",
                            Nombre = "Rumania"
                        },
                        new
                        {
                            Id = new Guid("8dd49756-22e3-4fac-9f5c-aabd596ea313"),
                            Codigo = "GI",
                            Nombre = "Gibraltar"
                        },
                        new
                        {
                            Id = new Guid("ec21f8b0-bf96-4027-8b25-6b6c2822fce4"),
                            Codigo = "SJ",
                            Nombre = "Islas Svalbard y Jan Mayen"
                        },
                        new
                        {
                            Id = new Guid("bf1414f3-e19c-4e53-9f24-02a5e24c9de3"),
                            Codigo = "AO",
                            Nombre = "Angola"
                        },
                        new
                        {
                            Id = new Guid("cdbc92ba-1fb2-4390-ae54-f210ef306fc1"),
                            Codigo = "BS",
                            Nombre = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("b47c9daa-06c9-4ae0-9ca4-0fe3c28abc45"),
                            Codigo = "SZ",
                            Nombre = "Suazilandia"
                        },
                        new
                        {
                            Id = new Guid("601b7882-f107-47e6-aa6e-d115fb30ab15"),
                            Codigo = "BR",
                            Nombre = "Brasil"
                        },
                        new
                        {
                            Id = new Guid("fe48301c-19ea-4608-a54e-6af873a62880"),
                            Codigo = "LT",
                            Nombre = "Lituania"
                        },
                        new
                        {
                            Id = new Guid("a1968f9a-0ed3-45cf-8cfb-f6c780c6b2e5"),
                            Codigo = "LC",
                            Nombre = "Santa Lucía"
                        });
                });

            modelBuilder.Entity("watchlistScreener.Server.Models.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionFisica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<double>("FacturacionAnual")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaUltimaEdicion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentificacionTributaria")
                        .HasColumnType("int");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefonico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SitioWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("watchlistScreener.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("watchlistScreener.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("watchlistScreener.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("watchlistScreener.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("watchlistScreener.Server.Models.Entities.Proveedor", b =>
                {
                    b.HasOne("watchlistScreener.Server.Models.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
